version: "3"
services:
    app:
        image: "ptrvsrg/daily-helper-api:1.0.0"
        container_name: "daily-helper-api-app"
        env_file:
            - ./.env
        ports:
            - "${DAILY_HELPER_PORT}:8080"
            - "${DAILY_HELPER_MAIL_PORT}:${DAILY_HELPER_MAIL_PORT}"
        networks:
            - daily-helper-api-net
        depends_on:
            - db
    db:
        image: "mariadb:latest"
        container_name: "daily-helper-api-db"
        restart: unless-stopped
        env_file:
            - ./.env
        volumes:
            - "daily-helper-api-db-data:/var/lib/mysql"
        networks:
            - daily-helper-api-net
volumes:
    daily-helper-api-db-data:
networks:
    daily-helper-api-net:
